default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: write-now_development

test:
  <<: *default
  database: write-now_test

production:
  <<: *default
  database: write-now_production
  username:
  password:
